### ISSUE TITLE
Support for adding a header in a http request

### ISSUE THREAD

**Issue by mik047** [featurehub-io/featurehub-java-sdk#11]
**Is your feature request related to a problem? Please describe.**
Our connectivity from client to FHIO is through a API gateway and it requires authentication. We would need a way in the mobile (android) sdk client to pass custom headers (along with the ones FHIO already sends) while talking to edge server

**Describe the solution you'd like**
Enhancement in API to add custom headers that the client would carry while making the request.

**Comment by rvowles** [comment]
So the Mobile client for Java is written in OKHttp 4.x - and that has support for interceptors on the client. Is there a reason you wouldn't add an interceptor to the client you pass into the FeatureHubClient?

**Comment by erhiteshkumar** [comment]
@rvowles We can add an interceptor on the client which is passed to the feature hub client.

**Comment by mik047** [comment]
So its checked to be working. Thanks for the input @rvowles :)
