### ISSUE TITLE
Duplicate class issue while using  client-java-android dependency in android project

### ISSUE THREAD

**Issue by erhiteshkumar** [featurehub-io/featurehub-java-sdk#5]
`dependencies {
   implementation 'io.featurehub.sdk:java-client-android:1.3'
  //Following didn't work
  // implementation ('io.featurehub.sdk:java-client-core:2.4') {
  //        exclude group: 'io.featurehub.sse.model', module: 'sse-edge-api'
  //    }
   implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.6.0'
    implementation 'androidx.appcompat:appcompat:1.4.0'
    implementation 'com.google.android.material:material:1.4.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.1'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
}

Dependency graph

+--- io.featurehub.sdk:java-client-core:2.+ -> 2.4
|    +--- org.jetbrains:annotations:22.0.0
|    +--- io.featurehub.strategies:strategy-matcher:1.1
|    |    \--- io.featurehub.edge:sse-edge-api:1.3
|    +--- org.apache.commons:commons-lang3:3.7
|    +--- io.featurehub.composites:composite-logging-api:1.1
|    |    +--- org.slf4j:jul-to-slf4j:1.7.25
|    |    |    \--- org.slf4j:slf4j-api:1.7.25
|    |    +--- org.slf4j:slf4j-api:1.7.25
|    |    \--- org.slf4j:jcl-over-slf4j:1.7.25
|    |         \--- org.slf4j:slf4j-api:1.7.25
|    \--- jakarta.annotation:jakarta.annotation-api:2.0.0

Both library ( java-client-core-2.4, sse-edge-api) having the common package(io.featurehub.sse.model) and class names) which is causing the issue.

Error log
-------------
Duplicate class io.featurehub.sse.model.Environment found in modules java-client-core-2.4 (io.featurehub.sdk:java-client-core:2.4) and sse-edge-api-1.3 (io.featurehub.edge:sse-edge-api:1.3)
Duplicate class io.featurehub.sse.model.FeatureState found in modules java-client-core-2.4 (io.featurehub.sdk:java-client-core:2.4) and sse-edge-api-1.3 (io.featurehub.edge:sse-edge-api:1.3)
Duplicate class io.featurehub.sse.model.FeatureStateUpdate found in modules java-client-core-2.4 (io.featurehub.sdk:java-client-core:2.4) and sse-edge-api-1.3 (io.featurehub.edge:sse-edge-api:1.3)
Duplicate class io.featurehub.sse.model.FeatureValueType found in modules java-client-core-2.4 (io.featurehub.sdk:java-client-core:2.4) and sse-edge-api-1.3 (io.featurehub.edge:sse-edge-api:1.3)
Duplicate class io.featurehub.sse.model.RoleType found in modules java-client-core-2.4 (io.featurehub.sdk:java-client-core:2.4) and sse-edge-api-1.3 (io.featurehub.edge:sse-edge-api:1.3)
Duplicate class io.featurehub.sse.model.RolloutStrategy found in modules java-client-core-2.4 (io.featurehub.sdk:java-client-core:2.4) and sse-edge-api-1.3 (io.featurehub.edge:sse-edge-api:1.3)
Duplicate class io.featurehub.sse.model.RolloutStrategyAttribute found in modules java-client-core-2.4 (io.featurehub.sdk:java-client-core:2.4) and sse-edge-api-1.3 (io.featurehub.edge:sse-edge-api:1.3)
Duplicate class io.featurehub.sse.model.RolloutStrategyAttributeConditional found in modules java-client-core-2.4 (io.featurehub.sdk:java-client-core:2.4) and sse-edge-api-1.3 (io.featurehub.edge:sse-edge-api:1.3)
Duplicate class io.featurehub.sse.model.RolloutStrategyFieldType found in modules java-client-core-2.4 (io.featurehub.sdk:java-client-core:2.4) and sse-edge-api-1.3 (io.featurehub.edge:sse-edge-api:1.3)
Duplicate class io.featurehub.sse.model.SSEResultState found in modules java-client-core-2.4 (io.featurehub.sdk:java-client-core:2.4) and sse-edge-api-1.3 (io.featurehub.edge:sse-edge-api:1.3)
Duplicate class io.featurehub.sse.model.StrategyAttributeCountryName found in modules java-client-core-2.4 (io.featurehub.sdk:java-client-core:2.4) and sse-edge-api-1.3 (io.featurehub.edge:sse-edge-api:1.3)
Duplicate class io.featurehub.sse.model.StrategyAttributeDeviceName found in modules java-client-core-2.4 (io.featurehub.sdk:java-client-core:2.4) and sse-edge-api-1.3 (io.featurehub.edge:sse-edge-api:1.3)
Duplicate class io.featurehub.sse.model.StrategyAttributePlatformName found in modules java-client-core-2.4 (io.featurehub.sdk:java-client-core:2.4) and sse-edge-api-1.3 (io.featurehub.edge:sse-edge-api:1.3)
Duplicate class io.featurehub.sse.model.StrategyAttributeWellKnownNames found in modules java-client-core-2.4 (io.featurehub.sdk:java-client-core:2.4) and sse-edge-api-1.3 (io.featurehub.edge:sse-edge-api:1.3)`

**Comment by rvowles** [comment]
You are right - strategy-matcher brings in 1.3 of sse-edge-api, which it should not do! I have released 2.5 - please let me know if that solves the problem for you?

**Comment by erhiteshkumar** [comment]
Thanks Richard it solves the issue.
