### ISSUE TITLE
get all feature state

### ISSUE THREAD

**Issue by axblueblader** [featurehub-io/featurehub-java-sdk#6]
Hi, i'm wondering is there or will there be support for getting all features and their state?
Something like:
```
client.getAllFeatures()
```

For more context, i want to get all the features that are toggled on for a specified user or user type
like
```
context.attr("userId",id).build.get()
```
then
```
client.getAllFeatures().stream().filter(FeatureState::isEnabled).map(FeatureState::getKey).collect(Collectors.toList());
```

**Comment by rvowles** [comment]
I don't see why not - its just a Map in the ClientFeatureRepository so adding that API would be easy.

**Comment by axblueblader** [comment]
Oh nice, was just wondering if there will be any design issues, if not i think i can help make a PR for it
