### ISSUE TITLE
Support Android SDK 21

### ISSUE THREAD

**Issue by rvowles** [featurehub-io/featurehub-java-sdk#8]
This would require a few changes and would support server evaluation only (no client side strategy matchers). The model would have to be manually maintained and probably GSON used instead of jackson.

**Comment by erhiteshkumar** [comment]
We need the required changes for  [client-java-android](https://github.com/featurehub-io/featurehub-java-sdk/tree/main/client-java-android)  to support Android SDK 21, currently  [client-java-android] it supports Android SDK 24 and above because it uses Supplier<T> and it is supported for android in above SDK 24.

**Comment by rvowles** [comment]
Sorry @erhiteshkumar - is the requirement Android SDK 21 or Java 6? It appears that OkHTTP 4.x supports Android 21+ and Java 8+ https://square.github.io/okhttp/#requirements

**Comment by rvowles** [comment]
It would seem you would strictly need Java 6 support, do you want to stay with OKHttp 4.x or go back to 3.x?

**Comment by rvowles** [comment]
@erhiteshkumar how do I go about determining what causes failures? I am not particularly familiar with Android and if there was a linting command or tool I could use that would be helpful?

**Comment by rvowles** [comment]
@erhiteshkumar ideally if we can have a simple Android project that is able to indicate build failure? It doesn't have to be runnable, just buildable. I can remove the use of Supplier as it is only internally, I'm just not sure what else I'm going to run into.

**Comment by erhiteshkumar** [comment]
[FeatureHubDemo.zip](https://github.com/featurehub-io/featurehub-java-sdk/files/8349827/FeatureHubDemo.zip)
I have attached the demo project. Currently minSdkVersion is 21 so it will give compilation error. if same is changed to 24 it will compile can run properly. minSdkVersion can be set in app > build.gradle file.

**Comment by erhiteshkumar** [comment]
@rvowles Please me know if zip is not accessible. Will share it by creating repository.

**Comment by rvowles** [comment]
Hi @erhiteshkumar - sorry I must have not made myself clear. I understand you wish for me to get rid of Supplier, no problem, I can do that, but how do I know what else might be in the SDK that will cause issues? I will create branch for you with it removed and if you can use the snapshot it builds to check it out? Just include mavenLocal() in your repository references and you should be good to go.

**Comment by rvowles** [comment]
@erhiteshkumar there is now a PR, if you could pull the repo down and build it ("mvn clean install" at the top level) and give it a go? I have had to clone the entire client and android SDK as the APIs have Supplier inbuilt into them and I cannot break the API.

**Comment by erhiteshkumar** [comment]
@rvowles Sorry for delay. Thanks!!! PR is working with Android SDK 21 and above. I am able to get the values.
